version: 2
updates:
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "daily"
      time: '10:00'
      timezone: "Europe/Berlin"
    labels:
      - "CI/CD"
    commit-message:
      prefix: ci
